version: '3.9'
services:
  basket_mongodb:
    container_name: linkeats-basket_mongodb
    restart: unless-stopped
    image: mongo:5.0
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_DATABASE=auth
      # - MONGO_INITDB_ROOT_PASSWORD=pass
    # networks: 
    #   - mongo-compose-network
    ports:
      - '27020:27017'
    volumes: 
      - ./.data/mongodb/basket_mongodb:/data/db
  order_mongodb:
    container_name: linkeats-order_mongodb
    restart: unless-stopped
    image: mongo:5.0
    ports:
      - '27018:27017'
    volumes: 
      - ./.data/mongodb/order_mongodb:/data/db
  dish_mongodb:
    container_name: linkeats-dish_mongodb
    restart: unless-stopped
    image: mongo:5.0
    ports:
      - '27019:27017'
    volumes: 
      - ./.data/mongodb/dish_mongodb:/data/db
  address_mongodb:
    container_name: linkeats-address_mongodb
    restart: unless-stopped
    image: mongo:5.0
    ports:
      - '27021:27017'
    volumes: 
      - ./.data/mongodb/address_mongodb:/data/db
  mssql:
    container_name: linkeats-mssql
    restart: unless-stopped
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password10_
      - MSSQL_PID=Express 
    ports:
      - '1434:1433'
    volumes: 
      - ./.data/mssql:/var/opt/mssql/data
  # front:
  #   container_name: linkeats-front
  #   restart: unless-stopped
  #   build: ./front
  #   depends_on:
  #     - nginx
  #   volumes:
  #     - ./front:/usr/src/app
  #   ports:
  #   - '8080:8080'
  api_doc:
    container_name: linkeats-api_doc
    restart: unless-stopped
    build: ./api_doc
    ports:
      - '3000:3000'
    volumes:
      - ./api:/usr/src/api_code:ro
  auth_api:
    container_name: linkeats-auth_api
    restart: unless-stopped
    build: ./api/auth_api
    depends_on:
      - mssql
    volumes: 
      - ./api/utils:/usr/src/app/src/utils:ro
  order_api:
    container_name: linkeats-order_api
    restart: unless-stopped
    build: ./api/order_api
    # deploy:
    #   mode: replicated
    #   replicas: 6
    depends_on:
      - order_mongodb
    volumes: 
      - ./api/utils:/usr/src/app/src/utils:ro
  basket_api:
    container_name: linkeats-basket_api
    restart: unless-stopped
    build: ./api/basket_api
    depends_on:
      - basket_mongodb
    volumes: 
      - ./api/utils:/usr/src/app/src/utils:ro
  dish_api:
    container_name: linkeats-dish_api
    restart: unless-stopped
    build: ./api/dish_api
    depends_on:
      - dish_mongodb
    volumes: 
      - ./api/utils:/usr/src/app/src/utils:ro
  address_api:
    container_name: linkeats-address_api
    restart: unless-stopped
    build: ./api/address_api
    depends_on:
      - address_mongodb
    volumes: 
      - ./api/utils:/usr/src/app/src/utils:ro
  # user_api:
    # container_name: linkeats-user_api
    # restart: unless-stopped
    # build: ./api/user_api
    # depends_on:
    #   - mssql
  clients_api:
    container_name: linkeats-clients_api
    restart: unless-stopped
    build: ./api/clients_api
    depends_on:
      - mssql
    volumes: 
      - ./api/utils:/usr/src/app/src/utils:ro
  restaurants_api:
    container_name: linkeats-restaurants_api
    restart: unless-stopped
    build: ./api/restaurants_api
    depends_on:
      - mssql
    volumes: 
      - ./api/utils:/usr/src/app/src/utils:ro
  developpers_api:
    container_name: linkeats-developpers_api
    restart: unless-stopped
    build: ./api/developpers_api
    depends_on:
      - mssql
    volumes: 
      - ./api/utils:/usr/src/app/src/utils:ro
  deliverymen_api:
    container_name: linkeats-deliverymen_api
    restart: unless-stopped
    build: ./api/deliverymen_api
    depends_on:
      - mssql
    volumes: 
      - ./api/utils:/usr/src/app/src/utils:ro
  nginx:
    container_name: linkeats-nginx
    restart: unless-stopped
    image: nginx:1.23
    depends_on:
      - auth_api
      - order_api
      - basket_api
      - clients_api
      - restaurants_api
      - deliverymen_api
      - developpers_api
      - address_api
      - dish_api
      # - api_doc
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/home/logs
    ports:
    - '80:80'
